import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/component/navbar/navbar'
import Caroussel from '@/component/Caroussel/caroussel'
import Footer from '@/component/Footer/Footer'
import Community from '@/component/Community/Community'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const allJsonData = await fetch('https://example-data.draftbit.com/books')
    .then(r => r.json())
  return {
    props: {
      allJsonData
    },
  };
}

export default function Home({allJsonData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Caroussel/>
    <Community/>
      <Footer/>
    </>
  )
}
